" To reload vimrc at every save
augroup reload_vimrc " {
	autocmd!
	autocmd BufWritePost $MYVIMRC source $MYVIMRC
augroup END " }
" Plugins managed by Vundle
source ~/.vim/plugins.vim

" Basic editor options
set encoding=utf-8
syntax on				" syntax highlighting
set number				" adds numbers to left side
set relativenumber		" relative numbers instead
set clipboard=unnamed		" clipboard to anywhere
set tabstop=4			" number of visual tabs
set shiftwidth=4			" number of spaces for 1 tab
set cursorline			" show line of cursor
set showmatch			" highlights matching brackets
set hlsearch			" highlight search

" Sortcuts
let mapleader = " "
nnoremap j gj
nnoremap k gk
inoremap jk <esc>
nnoremap <leader><space> :nohlsearch<cr>
nnoremap <leader>w :w<cr>
nnoremap <leader>q :q!<cr>
nnoremap <leader>\| :vsp<cr>
nnoremap <leader>_ :sp<cr>
nnoremap <leader>h :wincmd h<cr>
nnoremap <leader>j :wincmd j<cr>
nnoremap <leader>k :wincmd k<cr>
nnoremap <leader>l :wincmd l<cr>

" Quick edit handy files
nnoremap <leader>evr :e $MYVIMRC<cr>
nnoremap <leader>evp :e ~/.vim/plugins.vim<cr>
nnoremap <leader>ez  :e ~/.zshrc<cr>
nnoremap <leader>emf :e ~/dotfiles/Makefile<cr>
nnoremap <leader>etm :e ~/dotfiles/tmux/tmux.conf<cr>

" COLOR SCHEME
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

if filereadable(expand("~/.vim/vimrc_background"))
	let base16colorspace=256
	source ~/.vim/vimrc_background
endif
