" Reload vimrc at every save
augroup reload_vimrc " {
	autocmd!
	autocmd BufWritePost $MYVIMRC source $MYVIMRC
	autocmd BufWritePost ~/vim/aliases.vim source $MYVIMRC
augroup END " }
"

" Vim options
set encoding=utf-8
syntax on				" syntax highlighting
set number				" adds numbers to left side
set relativenumber		" relative numbers instead
set clipboard=unnamed		" clipboard to anywhere
set tabstop=4			" number of visual tabs
set shiftwidth=4			" number of spaces for 1 tab
set cursorline			" show line of cursor
set showmatch			" highlights matching brackets
set hlsearch			" highlight search

" Source vim aliases
source ~/.vim/aliases.vim

" Source vim plugins
source ~/.vim/plugins.vim

" Source vim colors
if filereadable(expand("~/.vimrc_background"))
	let base16colorspace=256
	source ~/.vimrc_background
endif
